/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { ActorDetails } from './actorDetails';

export interface ActorInsight {
	id: number;
	name: string;
	/** Number of times this actor appeared in reviewed movies */
	count: number;
	details: ActorDetails;
}
