/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface AdvancedScore {
	acting: number;
	characters: number;
	cinematography: number;
	climax: number;
	ending: number;
	music: number;
	personalScore: number;
	plot: number;
	theme: number;
	visuals: number;
}
