/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type CommentControllerFindAllParams = {
	/**
	 * Items per page (default: 20)
	 */
	pageSize?: number;
	/**
	 * Page number (default: 1)
	 */
	pageNumber?: number;
	/**
	 * MongoDB ObjectId of the post (review or comment)
	 */
	postId: string;
};
