/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type CommentPostType = (typeof CommentPostType)[keyof typeof CommentPostType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentPostType = {
	reviews: 'reviews',
	comments: 'comments',
} as const;
