/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface CommentVotesDto {
	/** Number of upvotes */
	upVote: number;
	/** Number of downvotes */
	downVote: number;
}
