/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { CommentAuthor } from './commentAuthor';
import type { CommentPostType } from './commentPostType';

export interface CommentPost {
	/** Post author profile details */
	author: CommentAuthor;
	id: string;
	type: CommentPostType;
}
