/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { CommentAuthorDto } from './commentAuthorDto';
import type { CommentPostDtoType } from './commentPostDtoType';

export interface CommentPostDto {
	/** Author of the parent post (review or comment) */
	author: CommentAuthorDto;
	/** ID of the parent post */
	id: string;
	/** Type of parent post */
	type: CommentPostDtoType;
}
