/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { CommentAuthorDto } from './commentAuthorDto';
import type { CommentPostDto } from './commentPostDto';
import type { CommentVotesDto } from './commentVotesDto';

export interface CommentResponseDto {
	_id: string;
	/** Comment author */
	author: CommentAuthorDto;
	comment: string;
	/** Parent post information */
	post: CommentPostDto;
	/** Vote counts */
	votes: CommentVotesDto;
	/** Whether the current user has upvoted this comment */
	hasUpvoted: boolean;
	/** Whether the current user has downvoted this comment */
	hasDownvoted: boolean;
	createdAt: string;
	updatedAt: string;
}
