/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { AdvancedScore } from './advancedScore';

export interface CreateReviewDtoClass {
	advancedScore: AdvancedScore;
	notes?: string;
	public: boolean;
	tmdbID: number;
	title: string;
	reviewedDate: string;
}
