/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchListMovie } from './watchListMovie';

export interface CreateWatchListDtoClass {
	title: string;
	description: string;
	/** Optional ordered list of TMDB movies */
	movies?: WatchListMovie[];
	tags?: string[];
	public: boolean;
}
