/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

/**
 * Type of post being commented on
 */
export type CreateCommentPostDtoType =
	(typeof CreateCommentPostDtoType)[keyof typeof CreateCommentPostDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateCommentPostDtoType = {
	reviews: 'reviews',
	comments: 'comments',
} as const;
