/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { CreateCommentPostDto } from './createCommentPostDto';

export interface CreateCommentDtoClass {
	/** The text content of the comment */
	comment: string;
	/** Reference to the parent post (review or comment) */
	post: CreateCommentPostDto;
}
