/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { CreateCommentPostDtoType } from './createCommentPostDtoType';

export interface CreateCommentPostDto {
	/** UID of the post author (review or comment author) */
	author: string;
	/** MongoDB ObjectId of the post (review or comment) */
	id: string;
	/** Type of post being commented on */
	type: CreateCommentPostDtoType;
}
