/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface CreateUserDto {
	/** User biography */
	bio?: string;
	/** User email address */
	email: string;
	/** Optional link */
	link?: string;
	/** User location */
	location?: string;
	/** Profile photo URL */
	photoUrl?: string;
	/** Whether the user profile is public */
	public: boolean;
	/** User display name/username */
	username: string;
	/** Country code associated with user */
	countryCode?: string;
}
