/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

/**
 * Reference to the parent post (review or comment)
 */
export type CreateCommentDtoClassPost = { [key: string]: unknown };
