/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type FeedControllerGetFeedParams = {
	/**
	 * Number of items per page
	 */
	pageSize?: string;
	/**
	 * Page number (1-indexed)
	 */
	pageNumber?: string;
	/**
	 * Whether to exclude the authenticated user's own reviews (default: true)
	 */
	excludeSelf?: string;
};
