/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { MovieGenre } from './movieGenre';

export interface FeedItemMovieDetails {
	id: number;
	title: string;
	overview: string;
	poster_path: string;
	backdrop_path: string;
	release_date: string;
	genres: MovieGenre[];
	vote_average: number;
	runtime: number;
}
