/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { GenreInsightItem } from './genreInsightItem';

export interface GenreInsight {
	/** Top 5 most reviewed genres by count */
	mostReviewedGenres: GenreInsightItem[];
	/** Genres ranked by affinity score (based on review count and ratings) */
	mostReviewedRankedGenres: GenreInsightItem[];
	/** Lowest ranked genres by affinity score */
	leastReviewedRankedGenres: GenreInsightItem[];
}
