/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type InsightControllerGetHeatmapInsightsParams = {
	/**
	 * Number of days to look back (default: 90)
	 */
	days?: number;
};
