/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { MovieBelongsToCollection } from './movieBelongsToCollection';
import type { MovieGenre } from './movieGenre';
import type { MovieProductionCompany } from './movieProductionCompany';
import type { MovieProductionCountry } from './movieProductionCountry';
import type { MovieSpokenLanguage } from './movieSpokenLanguage';
import type { MovieCredits } from './movieCredits';
import type { MovieReleaseDates } from './movieReleaseDates';
import type { Map } from './map';

export interface Movie {
	id: number;
	adult: boolean;
	backdrop_path: string;
	belongs_to_collection: MovieBelongsToCollection;
	budget: number;
	genres: MovieGenre[];
	homepage: string;
	imdb_id: string;
	original_country: string[];
	original_language: string;
	original_title: string;
	overview: string;
	popularity: number;
	poster_path: string;
	production_companies: MovieProductionCompany[];
	production_countries: MovieProductionCountry[];
	release_date: string;
	revenue: number;
	runtime: number;
	spoken_languages: MovieSpokenLanguage[];
	status: string;
	tagline: string;
	title: string;
	video: boolean;
	vote_average: number;
	vote_count: number;
	credits: MovieCredits;
	release_dates: MovieReleaseDates;
	updatedAt: string;
	watchProviders: Map;
}
