/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface MovieRegionReleaseDates {
	certification: string;
	iso_3166_1: string;
	note: string;
	release_date: string;
	type: number;
}
