/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface MovieProductionCompany {
	id: number;
	logo_path: string;
	name: string;
	origin_country: string;
}
