/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { MovieRegionReleaseDates } from './movieRegionReleaseDates';

export interface MovieReleaseDates {
	iso_3166_1: string;
	release_dates: MovieRegionReleaseDates[];
}
