/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface MovieWatchProvider {
	display_priority: number;
	logo_path: string;
	provider_id: number;
	provider_name: string;
}
