/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface MovieSpokenLanguage {
	iso_639_1: string;
	name: string;
	english_name?: string;
}
