/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { MovieCast } from './movieCast';
import type { MovieCrew } from './movieCrew';

export interface MovieCredits {
	cast: MovieCast[];
	crew: MovieCrew[];
}
