/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { MovieGenre } from './movieGenre';

export interface MovieDetails {
	id: number;
	backdrop_path: string;
	budget: number;
	genres: MovieGenre[];
	poster_path: string;
	release_date: string;
	revenue: number;
	runtime: number;
	title: string;
}
