/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationAggregatedContentType } from './notificationAggregatedContentType';
import type { NotificationContent } from './notificationContent';
import type { NotificationAggregatedNotificationType } from './notificationAggregatedNotificationType';
import type { NotificationSender } from './notificationSender';
import type { NotificationAggregatedContent } from './notificationAggregatedContent';

export interface NotificationAggregated {
	_id: string;
	contentId: string;
	contentType: NotificationAggregatedContentType;
	notificationContent: NotificationContent;
	notificationType: NotificationAggregatedNotificationType;
	recipient: string;
	sender: NotificationSender;
	content: NotificationAggregatedContent;
	isRead: boolean;
	createdAt: string;
	updatedAt: string;
}
