/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type NotificationAggregatedContentType =
	(typeof NotificationAggregatedContentType)[keyof typeof NotificationAggregatedContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationAggregatedContentType = {
	reviews: 'reviews',
	comments: 'comments',
	social: 'social',
} as const;
