/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationContentType } from './notificationContentType';
import type { NotificationContent } from './notificationContent';
import type { NotificationNotificationType } from './notificationNotificationType';

export interface Notification {
	contentId: string;
	contentType: NotificationContentType;
	notificationContent: NotificationContent;
	notificationType: NotificationNotificationType;
	recipient: string;
	sender: string;
	isRead: boolean;
	createdAt: string;
	updatedAt: string;
}
