/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type NotificationNotificationType =
	(typeof NotificationNotificationType)[keyof typeof NotificationNotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationNotificationType = {
	comment: 'comment',
	dislike: 'dislike',
	like: 'like',
	follow: 'follow',
	unfollow: 'unfollow',
} as const;
