/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type NotificationAggregatedNotificationType =
	(typeof NotificationAggregatedNotificationType)[keyof typeof NotificationAggregatedNotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationAggregatedNotificationType = {
	comment: 'comment',
	dislike: 'dislike',
	like: 'like',
	follow: 'follow',
	unfollow: 'unfollow',
	viewed: 'viewed',
} as const;
