/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { ReviewAggregated } from './reviewAggregated';
import type { ReviewControllerFindMostReviewedV2200ItemAllOf } from './reviewControllerFindMostReviewedV2200ItemAllOf';

export type ReviewControllerFindMostReviewedV2200Item = ReviewAggregated &
	ReviewControllerFindMostReviewedV2200ItemAllOf;
