/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type ReviewControllerFindByTmdbIdParams = {
	/**
	 * Items per page (default: 10)
	 */
	pageSize?: number;
	/**
	 * Page number (default: 1)
	 */
	pageNumber?: number;
};
