/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { ReviewAggregated } from './reviewAggregated';

export type ReviewControllerFindByActorId200 = {
	/** Average of averagedAdvancedScore across matching reviews */
	averagedReviewScore?: number;
	results?: ReviewAggregated[];
};
