/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { AdvancedScore } from './advancedScore';
import type { ReviewVotes } from './reviewVotes';
import type { Profile } from './profile';
import type { MovieDetails } from './movieDetails';

export interface ReviewAggregated {
	_id: string;
	userId: string;
	averagedAdvancedScore: number;
	tmdbID: number;
	advancedScore: AdvancedScore;
	public: boolean;
	title: string;
	votes: ReviewVotes;
	createdAt: string;
	updatedAt: string;
	reviewedDate: string;
	notes: string;
	/** User profile information (joined) */
	profile: Profile;
	/** TMDB movie details (joined) */
	movieDetails: MovieDetails;
}
