/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type ReviewControllerFindByUserIdParams = {
	/**
	 * Sort results by field. Format: "field.order" or "field.order.category" where order is "asc" or "desc". Examples: "title.asc", "averagedAdvancedScore.desc", "advancedScore.desc.acting".
	 */
	sortBy?: string;
	/**
	 * Filter by an advanced score. Format: "category.score" or "category.subcategory.score" (example: "acting.8").
	 */
	advancedScore?: string;
	/**
	 * Filter by TMDB movie ID (integer).
	 */
	tmdbId?: number;
	/**
	 * Filter reviews by movie genre name (example: Adventure).
	 */
	genre?: string;
	/**
	 * Full-text search across title/notes. Optional. Pass a string to search for.
	 */
	textSearch?: string;
	/**
	 * Items per page (default: 10)
	 */
	pageSize?: number;
	/**
	 * Page number (default: 1)
	 */
	pageNumber?: number;
};
