/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { ReviewControllerFindByTmdbId200AllOf } from './reviewControllerFindByTmdbId200AllOf';
import type { ReviewControllerFindByTmdbId200AllOfTwo } from './reviewControllerFindByTmdbId200AllOfTwo';

export type ReviewControllerFindByTmdbId200 = ReviewControllerFindByTmdbId200AllOf &
	ReviewControllerFindByTmdbId200AllOfTwo;
