/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface UpdateUserDto {
	/** User biography */
	bio?: string;
	/** User email address */
	email?: string;
	/** Optional link */
	link?: string;
	/** User location */
	location?: string;
	/** Profile photo URL */
	photoUrl?: string;
	/** Whether the user profile is public */
	public?: boolean;
	/** User display name/username */
	username?: string;
	/** Country code associated with user */
	countryCode?: string;
	/** Array of pinned review IDs (ObjectIds) */
	pinned?: string[];
	/** Array of follower user IDs (ObjectIds) */
	followers?: string[];
	/** Array of user IDs this user is following (ObjectIds) */
	following?: string[];
}
