/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface User {
	/** User biography */
	bio: string;
	/** User email address */
	email: string;
	/** User first name */
	firstName: string;
	/** User last name */
	lastName: string;
	/** Array of follower user IDs (ObjectIds) */
	followers: string[];
	/** Array of user IDs this user is following (ObjectIds) */
	following: string[];
	/** User location */
	location: string;
	/** URL to user profile photo */
	photoUrl: string;
	/** Whether the user profile is public */
	public: boolean;
	/** Timestamp when the user was created */
	createdAt: string;
	/** Timestamp when the user was last updated */
	updatedAt: string;
	/** Firebase unique identifier (UUID) */
	uuid: string;
	/** Array of pinned review IDs (ObjectIds) */
	pinned: string[];
	/** Array of device identifiers associated with the user */
	devices: string[];
	/** User display name/username */
	username: string;
	/** Country code(s) associated with user */
	countryCodes: string;
}
