/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface UserProfileWithWatchedCount {
	/** MongoDB ObjectId */
	_id: string;
	/** Firebase unique identifier (UUID) */
	uuid: string;
	/** User display name/username */
	username: string;
	/** User biography */
	bio: string;
	/** User location */
	location: string;
	/** Whether the user profile is public */
	public: boolean;
	/** URL to user profile photo */
	photoUrl: string;
	/** Total follower count */
	followerCount: number;
	/** Total following count */
	followingCount: number;
	/** Total review count */
	reviewCount: number;
	/** Total watchlist count */
	watchListCount: number;
	/** Country code(s) associated with user */
	countryCodes?: string;
	/** Whether the requesting user follows this user */
	isFollowing: boolean;
	/** Timestamp when the user joined */
	joinedAt: string;
	/** Total watched item count for the user */
	watchedCount: number;
}
