/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type UserControllerGetFollowingParams = {
	/**
	 * Page number (1-indexed)
	 */
	pageNumber?: number;
	/**
	 * Number of results per page
	 */
	pageSize?: number;
	/**
	 * Search users by username
	 */
	search?: string;
};
