/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { VoteCommentDtoClassVoteType } from './voteCommentDtoClassVoteType';

export interface VoteCommentDtoClass {
	/** Type of vote to apply (up or down) */
	voteType: VoteCommentDtoClassVoteType;
}
