/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

/**
 * Type of vote to apply (up or down)
 */
export type VoteCommentDtoClassVoteType =
	(typeof VoteCommentDtoClassVoteType)[keyof typeof VoteCommentDtoClassVoteType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteCommentDtoClassVoteType = {
	up: 'up',
	down: 'down',
} as const;
