/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { MovieWatchProviders } from './movieWatchProviders';

export interface WatchlistMovieAggregated {
	order: number;
	tmdbID: number;
	id: number;
	title: string;
	poster_path: string;
	backdrop_path: string;
	release_date: string;
	overview: string;
	watchProviders?: MovieWatchProviders;
	/** Number of reviews the user has for this movie */
	reviewCount: number;
}
