/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchListMovie } from './watchListMovie';

export interface Watchlist {
	createdAt: string;
	description: string;
	/** Array of movies in the watch list */
	movies: WatchListMovie[];
	public: boolean;
	tags: string[];
	title: string;
	updatedAt: string;
	userId: string;
}
