/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type WatchedControllerFindByUserIdParams = {
	/**
	 * Filter by release or watched year
	 */
	year?: number;
	/**
	 * Filter by liked
	 */
	liked?: boolean;
	/**
	 * e.g., watchedDate.desc, createdAt.desc, title.asc
	 */
	sortBy?: string;
	/**
	 * Items per page (default: 20)
	 */
	pageSize?: number;
	/**
	 * Page number (default: 1)
	 */
	pageNumber?: number;
};
