/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export type WatchListControllerGetUserWatchListsParams = {
	/**
	 * Sort results by field. Format: "field.order" or "field.order.category" where order is "asc" or "desc". Examples: "title.asc", "updatedAt.desc".
	 */
	sortBy?: string;
	/**
	 * Comma-separated TMDB movie IDs to filter by
	 */
	tmdbId?: string;
	/**
	 * Search watch list titles or descriptions
	 */
	textSearch?: string;
	/**
	 * Items per page (default: 10)
	 */
	pageSize?: number;
	/**
	 * Page number (default: 1)
	 */
	pageNumber?: number;
};
