/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface WatchlistMovieAggregatedSummary {
	order: number;
	tmdbID: number;
	id: number;
	title: string;
	poster_path: string;
	backdrop_path: string;
	release_date: string;
	overview: string;
	/** Number of reviews the user has for this movie */
	reviewCount: number;
	/** Whether the user has marked this movie as watched */
	watched: boolean;
}
