/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */

export interface WatchedMovieDetails {
	id: number;
	title: string;
	original_title: string;
	poster_path: string;
	backdrop_path: string;
	release_date: string;
	vote_average: number;
}
