/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchedControllerFindByUserId200ResultsItem } from './watchedControllerFindByUserId200ResultsItem';

export type WatchedControllerFindByUserId200 = {
	pageNumber?: number;
	pageSize?: number;
	totalNumberOfPages?: number;
	totalCount?: number;
	results?: WatchedControllerFindByUserId200ResultsItem[];
};
