/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchlistMovieAggregated } from './watchlistMovieAggregated';

export interface WatchlistAggregated {
	_id: string;
	createdAt: string;
	description: string;
	/** Array of movies with full TMDB details */
	movies: WatchlistMovieAggregated[];
	public: boolean;
	tags: string[];
	title: string;
	updatedAt: string;
	userId: string;
}
