/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchedAggregated } from './watchedAggregated';
import type { WatchedControllerFindByUserId200ResultsItemAllOf } from './watchedControllerFindByUserId200ResultsItemAllOf';

export type WatchedControllerFindByUserId200ResultsItem = WatchedAggregated &
	WatchedControllerFindByUserId200ResultsItemAllOf;
