/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchlistAggregated } from './watchlistAggregated';

export type WatchListControllerGetUserWatchLists200 = {
	/** Current page number (1-indexed) */
	pageNumber?: number;
	/** Number of items per page */
	pageSize?: number;
	/** Total number of pages */
	totalNumberOfPages?: number;
	/** Total number of documents matching the query */
	totalCount?: number;
	/** Array of results in the current page */
	results?: WatchlistAggregated[];
};
