/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchedMovieDetails } from './watchedMovieDetails';

export interface WatchedAggregated {
	_id: string;
	userId: string;
	tmdbId: number;
	liked: boolean;
	watchedDate: string;
	createdAt: string;
	updatedAt: string;
	/** Joined TMDB movie details */
	movieDetails: WatchedMovieDetails;
}
