/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TMREV API v2
 * Review aggregation and movie database API
 * OpenAPI spec version: 2.0.0
 */
import type { WatchlistMovieAggregatedDetail } from './watchlistMovieAggregatedDetail';

export interface WatchlistAggregatedDetail {
	_id: string;
	createdAt: string;
	description: string;
	/** Array of movies with full TMDB details and providers */
	movies: WatchlistMovieAggregatedDetail[];
	public: boolean;
	tags: string[];
	title: string;
	updatedAt: string;
	userId: string;
	/** Average advanced score across all reviewed movies */
	averageAdvancedScore: number;
	/** Percentage of movies in the list that have been reviewed or marked as watched */
	completionPercentage: number;
	/** Total budget of all movies in the list */
	totalBudget: number;
	/** Total runtime of all movies in the list (in minutes) */
	totalRuntime: number;
}
